### ISSUE TITLE
Bot hangs when two users invokes it at the same time

### ISSUE THREAD

**Issue by HerrCraziDev** [Deivu/Kongou#17]
Whenever two users happens to invoke the bot at roughly the same time, or otherwise while the bot is connecting to a voice channel, the bot hangs and further calls crashes.

Log sample : 
```
Dec 16 22:26:33 kirishima-test node[96154]: [Process 96154] [Cluster 0]  Error: Can't connect while a connection is connecting. Wait for it to resolve first
Dec 16 22:26:33 kirishima-test node[96154]:     at ShoukakuConnection.connect ([...]/node_modules/shoukaku/src/guild/ShoukakuConnection.js:132:19)
Dec 16 22:26:33 kirishima-test node[96154]:     at ShoukakuSocket.joinChannel ([...]/node_modules/shoukaku/src/node/ShoukakuSocket.js:219:37)
Dec 16 22:26:33 kirishima-test node[96154]:     at Map.handle ([...]/src/modules/Queue.js:12:39)
Dec 16 22:26:33 kirishima-test node[96154]:     at Play.run ([...]/src/interactions/music/Play.js:60:52)
Dec 16 22:26:33 kirishima-test node[96154]:     at runMicrotasks (<anonymous>)
Dec 16 22:26:33 kirishima-test node[96154]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 16 22:26:33 kirishima-test node[96154]:     at async InteractionHandler.exec ([...]/src/modules/InteractionHandler.js:107:13)
```

**Probable solution :** catch and handle the exception in `Queue.handle()`

**Comment by Deivu** [comment]
We could just try catch the connection, join channel method, then if the error name is equal to that, we can safely ignore and inform the user that a connection is conencting

**Comment by HerrCraziDev** [comment]
Yup, I'll look into fixing it asap :)

**Comment by Deivu** [comment]
Fixed
